### ISSUE TITLE
WakeLock eating battery

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#258]
_Original author: inshame@gmail.com (June 13, 2012 12:31:56)_

<b>What steps will reproduce the problem?</b>
1. I just used the program to update my lists manually.

 com.commonsware.cwac.wakeful.WakefulIntentService (org.adaway.AdAway): 9 h 31 m 25 s  (34285 s) Count:0 95.8&#37;

This WakeLock was stuck all night open and ate my battery. 

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=257_

**Comment by 0-kaladin** [comment]
Not reproducible, will wait if any new issues on latest version.
