### ISSUE TITLE
Adaway aks for root and closes / black screen / root access takes too long

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#350]
Some bugs are merged in this bug:
- sometimes root access takes too long (timeout)
- this results in black screen or closes

also on:
- note 2 using a touchwiz based rom running 4.1.2

<b>What steps will reproduce the problem?</b>
Updating or installing the aplication is asking for root access

<b>What is the expected output? What do you see instead?</b>
a window asking that Adaway needs root access in order to run, and closes after accepting it.

<b>Please enable Debug Logging in preferences of AdAway, install aLogcat and</b>
<b>save a logfile while reproducing the problem. The logfile can be attached</b>
<b>to this issue.</b>
Cant Enter Adway. 
Tried uninstalling it using the default uninstaller from market and tested clearing cache but it still shows the same root window message.

What version of AdAway are you using? What Android version? What custom rom?
- Lastest Adaway version from market
- Android 2.2, Spanish, 
- ZTE-BLADE Build FRF91.
- Kernel 2.6.32.9-perf
- Root mobile with z4-root permanent root and SuperUser Manager.
- Link2SD.
- Default ZTE room.

<b>Please provide any additional information below.</b>
NA

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=349_

**Comment by 0-kaladin** [comment]
All this should have been fixed with the davisnt patch to rootcommands as there have been no reports of root issues since that time.  This is old enough it would have to be a new issue opened against the latest version.
