### ISSUE TITLE
Ads in Panda Run

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#361]
_Original author: phl...@gmail.com (December 15, 2012 05:01:13)_

<b>What steps will reproduce the problem?</b>
1. Install and run the game &quot;Panda Run &quot;
2.load
3.ads show

<b>What is the expected output? What do you see instead?</b>
No ad

<b>Please enable Debug Logging in preferences of AdAway, install aLogcat and</b>
<b>save a logfile while reproducing the problem. The logfile can be attached</b>
<b>to this issue.</b>

<b>What version of AdAway are you using? What Android version? What custom</b>
<b>rom?</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=360_

**Comment by 0-kaladin** [comment]
follow this https://github.com/Free-Software-for-Android/AdAway/wiki/Solutions to figure out what to blacklist.  Unless Panda run shows up in adware scan then potentially it uses something like airpush.
