### ISSUE TITLE
Rebooting disables Adaway on Galaxy S3

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#369]
_Original author: HDK...@gmail.com (December 22, 2012 17:13:31)_

<b>What steps will reproduce the problem?</b>
1. Launch app
2. Download and apply new hosts
3. Reboot 

Sometime after a reboot, I would see a notification about an ad, then launch Adaway to find out it is disabled. I will enable, apply new patches and would work fine. 

<b>Please enable Debug Logging in preferences of AdAway, install aLogcat and</b>
<b>save a logfile while reproducing the problem. The logfile can be attached</b>
<b>to this issue.</b>

<b>What version of AdAway are you using? What Android version? What custom</b>
<b>rom?</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=368_

**Comment by 0-kaladin** [comment]
This is generally not an AdAway issue but rather an issue with root on the device, write access to system or the rom overwriting the hosts file with its own changes (this is likely since you mentioned clean rom).  work with the clean rom dev to prevent that.
