### ISSUE TITLE
Experimental SPDY Data Compression Proxy from Chrome Beta breaks Ad Blocker functionality

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#404]
_Original author: HebeGu...@gmail.com (March 06, 2013 06:46:30)_

<b>What steps will reproduce the problem?</b>
1. Install newest chrome beta.
2. Type chrome://flags then enable the Experimental Data Compression Proxy.
3. Tada.. The ad mob traffic now suspect to flow through the proxy too.

<b>What is the expected output? What do you see instead?</b>
Nothing, just wanna to raise the issue. Hopefully more thorough inspection can be done to inspect how much others traffic it penetrating AdAway.

Best solutions and wishes --&gt; a fixed.

<b>What version of AdAway are you using? What Android version? What custom</b>
<b>rom?</b>
AdAway 2.1, Chrome Beta 26.0.1410.26, Android 4.1.1 and ViperX 3.3.8

<b>Please provide any additional information below.</b>

For extra information read this:
http://www.androidpolice.com/2013/03/05/newest-chrome-beta-for-android-includes-experimental-spdy-data-compression-proxy-for-faster-browsing/

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=403_

**Comment by 0-kaladin** [comment]
This can be closed.  Its the same as if you have an APN proxy configured, using the data compression option in any browser has the browser use a proxy of its own for loading all sites.  Using any proxy, whether APN, browser, etc will always defeat the Adaway hosts file entries.  Luckily there is always an option to turn off the compression proxies.
