### ISSUE TITLE
Automatic update stopped working

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#412]
_Original author: drlaurid...@gmail.com (March 12, 2013 21:45:47)_

<b>What steps will reproduce the problem?</b>
Automatic update seems to be broken.  For quite some time I have not received notifications about updates,  but when I check manually,  updates are found and also applied correctly. 

What version of AdAway are you using? What Android version?
Latest AdAway, android 4.2.1 but same with 4.0.3 on another phone..

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=411_

**Comment by 0-kaladin** [comment]
update is working on latest for me on 2 devices.  would have to retest on latest version and open new issue since this is so old.
