### ISSUE TITLE
MXPlayer ad

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#415]
_Original author: duwc...@gmail.com (March 14, 2013 04:30:51)_

<b>What steps will reproduce the problem?</b>
<b>1.</b>
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>Please enable Debug Logging in preferences of AdAway, install aLogcat and</b>
<b>save a logfile while reproducing the problem. The logfile can be attached</b>
<b>to this issue.</b>

<b>What version of AdAway are you using? What Android version? What custom</b>
<b>rom?</b>

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=414_

**Comment by 0-kaladin** [comment]
This is simply a matter of adding hosts to your blacklist.  It's been discovered in the forums that MX player pulls ads from facebook.  If you are ok with losing access to facebook then add graph.facebook.com and/or *.facebook.com to your blacklist.
OR you can buy MX player to remove ads if you use it that much and also want to use facebook.

**Comment by jinsonkv** [comment]
You can use the [MX player PRO apk](https://www.unknownguides.com/mx-player-pro-apk/) to fix ads issue.
