### ISSUE TITLE
inmobi ads in mx player

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#429]
_Original author: cpu...@gmail.com (March 30, 2013 00:43:39)_

How to block them? What host to use in blacklist?

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=428_

**Comment by 0-kaladin** [comment]
its been found mx player pulls ads from facebook urls.  Either add facebook to block list or buy mx player to remove the ads.
