### ISSUE TITLE
Blocking adf.ly links

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#442]
_Original author: sumanta...@gmail.com (May 31, 2013 03:44:44)_

Adaway blocks unwanted sites like http://adf.ly/H1JrK which we will be redirects to the downloading link.This create a huge problem. This type of links should not be blocked

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=441_

**Comment by 0-kaladin** [comment]
just follow this: https://github.com/Free-Software-for-Android/AdAway/wiki/Solutions to created the whitelist you need.
