### ISSUE TITLE
Airdroid not work under adaway

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#448]
_Original author: roosydin...@gmail.com (June 11, 2013 14:16:37)_

<b>What steps will reproduce the problem?</b>
1.activate adaway
2.run airdroid

expected running airdroid
see nothing instead

Adaway 2.3
Android 2.1 
NOOK Manager

already in white list:
server.airdroid.com
airdroid.com

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=447_

**Comment by 0-kaladin** [comment]
I still use airdroid and still no issues....
