### ISSUE TITLE
Latest update of hostsinterfering with Playstore v4.1.6 on AOSP Gingerbread 2.3.7 and CM 9 ICS 4.0.4

### ISSUE THREAD

**Issue by dschuermann** [Free-Software-for-Android/AdAway#451]
_Original author: tommie.b...@gmail.com (June 15, 2013 21:25:19)_

Google play error RPCS 5 AEC 0 with latest Adaway hosts file perhaps causes issues in updating apps.  Look at comment here - http://productforums.google.com/d/msg/mobile/2UKJ7ZyIav0/w-T1o2iWA2wJ

_Original issue: http://code.google.com/p/ad-away/issues/detail?id=450_

**Comment by 0-kaladin** [comment]
no longer valid
