### ISSUE TITLE
AdAway hangs or appears to crash when installing and reverting hosts files on Note 3

### ISSUE THREAD

**Issue by fatfurrycat** [Free-Software-for-Android/AdAway#475]
I have a SIM free unbranded Galaxy Note 3 running firmware:
AP: N9005XXUBMJ3
CP: N9005XXUBMJ2
CSC: N9005OXABMJ3

I have rooted using Root de la Vega, and am running Super SU Pro 1.65.
I have also installed BusyBox 1.21.1 using the BusyBox Pro app.

I am running AdAway v2.8, downloaded from F-Droid.

When I first installed AdAway, I got a prompt for SU access, which I granted. 
I then did the following:

1) Click "Download files and apply ad blocking". The app crashed.

2) I re-opened the application and clicked "Download files and apply ad blocking".
    This time I got a pop up saying "Copying of host file failed".

3) I then rebooted the Note 3, launched AdAway again, and clicked "Download files and apply ad blocking".

This time it was successful, and the Ad blocks are in place.

However, when I try to update the hosts files, I often find that the application hangs completely, and eats loads of CPU. My battery drains very rapid, and AdAway cannot be killed using the normal Android task managers. If I look at SuperSU logs, all I see is:

AdAway @ 01/11 19:29
echo Started
Started

When I attempt to disable ad blocking, I see a message which says 'Reverting. Creating standard hosts file." 

This also either hangs forever (well, for more then 2 hours), or I get a message after about 10 minutes saying that the operation failed. 

I've installed aLogcat and enabled debug mode in AdAway. However, I cannot capture any AdAway related log messages. I've tried all of the log levels from Verbose to Fatal, and the only message captured says "D/AbsListView unregisterIRListener() is called"

I'd be happy to capture more diagnostic information, but would appreciate some pointers on how to configure aLogCat to capture AdAway messages.

There are some similar reports here:
http://forum.xda-developers.com/showthread.php?t=2475328

**Comment by 0-kaladin** [comment]
This has probably been fixed, would require re-testing on latest version.
