### ISSUE TITLE
Videos on FilmOn app Not working

### ISSUE THREAD

**Issue by ZEKE3rd** [Free-Software-for-Android/AdAway#479]
After Enabled Adaway

Channels or videos on FilmOn app doesn't work , it's give me a black screen

i tried to add links to the whitelist Like:
us.filmon.com
filmon.com
204.107.26.109

but still not working.
![screenshot_-----](https://f.cloud.github.com/assets/5924863/1528374/bde463a6-4c09-11e3-8019-4f2fb0baf2ff.png)

**Comment by 0-kaladin** [comment]
Both these play videos for me during my quick test.  The only thing i can suggest when adding to whitelist, is instead of adding something very specific like us.filmon.com you can instead cover your bases by adding ``*filmon.com`` so any requests to filmon will be allowed.
