### ISSUE TITLE
url redirected from xiti.com

### ISSUE THREAD

**Issue by LTHxxx** [Free-Software-for-Android/AdAway#482]
got a trouble with some links from twitter, for example

Philippe Berry (@ptiberry) a tweeté à 11:51 PM on ven., nov. 22, 2013 :
Les Tontons flingueurs en deuil: son réalisateur, Georges Lautner, est mort à 87 ans http://t.co/djaz5bBgP5
(https://twitter.com/ptiberry/status/404019415349338112)

drive me to this url

http://logi4.xiti.com/go.url?xts=290428&xtor=AL-125&url=http://www.20minutes.fr/article/1253601/20min

obviously AdAway blocks xiti.com
any way to keep on blocking xiti.com but keep the usefull part of the url http://www.20minutes.fr/article/1253601/20min ?

**Comment by 0-kaladin** [comment]
No since twitter sent you through xiti.  Just add logi4.xiti.com to your whitelist or *xiti.com if needed.
