### ISSUE TITLE
Null pointer with android 4.4 ART Runtime

### ISSUE THREAD

**Issue by tux-mind** [Free-Software-for-Android/AdAway#483]
using adaway 2.6 on android 4.3 => no problems :thumbsup: .

after updated to 4.4 i noticed a broken pipe ( EPIPE ) bug, updating to 2.8 solved the EPIPE bug but i got another one.
this time is a Null Pointer :scream: 

my phone:
Nexus 4 16GB - Android AOSP 4.4 - ART Runtime enabled - SuperSu 1.80

logcat ( i filtered the process pid ): http://pastebin.com/AdxGvHBG

i'm available for any other info.

happy debugging :stuck_out_tongue_winking_eye: 

PS:
i found the EPIPE bug while developing dSploit. SuperSU give you a maximum of 3 root shells in a certain time period, so i think that you solved that bug by switching to RootCommands library.

i developed a [Shell.java](https://github.com/evilsocket/dsploit/blob/improved_shell/dSploit/src/it/evilsocket/dsploit/core/Shell.java) that allow you to run multiple commands ( asynchronously too ) using only one root shell, you can use it if this bug had the same reason of the EPIPE one.

**Comment by 0-kaladin** [comment]
I don't believe this is still occurring.  If so I'd request a new logcat on the latest version of Adaway.  thanks.
