### ISSUE TITLE
ad-away 2.8 identified as malware by Junos Pulse antivirus

### ISSUE THREAD

**Issue by epic2000** [Free-Software-for-Android/AdAway#484]
Junos Pulse antivirus identifies AdAway as containing critical malware (A.HEUR.Sig.0000827) and requires it to be uninstalled.

Juniper Networks Junos Pulse v.4.2.9.40119
Antivirus Signatures Version: 199
Malware Rules Version: 199
Prohibited Version: 158

Android 4.3 (CM10.2) on HTC Sensation

**Comment by 0-kaladin** [comment]
if there is no further update here, since this is so old then I'd close this out.
