### ISSUE TITLE
Applying filters fails often, hangs daemonsu

### ISSUE THREAD

**Issue by paour** [Free-Software-for-Android/AdAway#492]
On a Galaxy S3 running CM 10.2, with SuperSU 1.80, Adaway 2.8 often fails to apply filter changes (after successfully downloading the various files). When it does, it leaves one of the daemonsu:nnnnn processes in such a state that the process consumes 100% of one core and keeps the CPU awake, running down the battery.

What sort of logs should I provide so that you can investigate and fix the issue?

**Comment by Arinerron** [comment]
Please check issue #476
