### ISSUE TITLE
AdAway not finding su binary

### ISSUE THREAD

**Issue by Musashi69** [Free-Software-for-Android/AdAway#499]
Running OmniROM nightly (Android 4.4.2) on am i9305 with working SuperSu 1.89 installed. 

When trying to start AdAway it complains about not finding su binary or that I didn't grant privileges. In SuperSu logs there's no record of AdAway asking for root privileges. Clearing Adaway's app data didn't solve the problem, neither did un- and reinstalling the app. I got AdAway 2.8 through f-droid.org app. 

Any hints what's wrong here? Cam I help you to track this down? If so - how?

**Comment by 0-kaladin** [comment]
Closing for age would need to be retested on latest version.
