### ISSUE TITLE
adaway crashes when xposed module is installed

### ISSUE THREAD

**Issue by lvuser** [Free-Software-for-Android/AdAway#501]
Adaway crashes when it is phrasing and merging the hosts file. When xposed framework is disabled, it works fine. When it is enabled back, it crashes again.

I am using this adblock list: http://adblock.mahakala.is/  (File is 12.51 MB).
Adblock list source: http://forum.xda-developers.com/showthread.php?t=1916098

If I use the normal adblock lists that comes with adaway, it works fine. When I add the large list, it crashes. It only crashes when Xposed framework is installed. 

Not sure if it is a bug in adaway or it has to do with Xposed framework causing some issues. The xposed modules I got are XPrivacy, Greenify and Burnt toast, if it makes any difference.

OS: Android 4.4.2 (CM 11 Nightly)

logcat log: https://www.dropbox.com/s/p7teet7tgejcynw/adaway-log.txt

**Comment by 0-kaladin** [comment]
see response on issue #633
