### ISSUE TITLE
The app “TVSpielfilm“ is loading very slowly.

### ISSUE THREAD

**Issue by AudiS1** [Free-Software-for-Android/AdAway#504]
The app "TVSpielfilm" is loading very slowly when AdAway is activated.
Please fix this problem.

**Comment by 0-kaladin** [comment]
This isn't an issue with adaway but rather (potentially) a domain that needs to be whitelisted.  Please follow this: https://github.com/Free-Software-for-Android/AdAway/wiki/Solutions
to figure out what needs to be whitelisted and reply here once found and we can add it to the wiki to help others.
