### ISSUE TITLE
Rebooting disables Adaway on Huawei Ascend Mate

### ISSUE THREAD

**Issue by jonbenz** [Free-Software-for-Android/AdAway#510]
Hi guys,

After a sucessful host file download and applying. The app restart the phone, but when i open it again, the protection is disabled.

Huawei Ascend Mate
HYD52ROM V5 (Jelly Bean 4.2.2)
Adaway version - 2.8
SuperSU (Root Access)

I enabled Debug Logging and installed aLogcat, but i couldn't find any log to save.

Before i had installed this new rom, i was using huawei's stock rom and Adaway was working perfectly.

Thanks for your help.

**Comment by 0-kaladin** [comment]
This is not an AdAway problem.  something in this rom is overwriting the hosts file or reverting it to a stock format.  It may have had its own ad blocker. best to contact the rom dev to figure it out.
