### ISSUE TITLE
Adaway meddles with Feedly and apps using Feedly's API

### ISSUE THREAD

**Issue by diesocke** [Free-Software-for-Android/AdAway#512]
I recently detected that it was Adaway that stopped my RSS app Feedly from working properly. I couldn't log in anymore until I either deactivated Adaway. Now I put "feedly.com" and "*.feedly.com" on the whitelist. And now it's working again.

I don't know yet if this is a commom problem or one related to the 8 blocklists I happen to use.

**Comment by 0-kaladin** [comment]
Yea it isn't adaway but rather your blocklists.  Either reduce your blocklists (find the one that is blocking feedly) or add the whitelist as you did.  Both solve your issue.
