### ISSUE TITLE
USB tether not working on Sony Xperia E Dual 

### ISSUE THREAD

**Issue by ryshic12** [Free-Software-for-Android/AdAway#515]
USB tethering fails. (Phone shows tethering. PC doesn't detect anything) on my Xperia E Dual running ICS 4.0.4. (build no 11.1.A.0.68)

Disabling AdAway automatically fixes this!

**Comment by 0-kaladin** [comment]
Closing for age and I can't imagine how this is adaway.  Regardless, retest on latest version, open new issue.
