### ISSUE TITLE
UPDATE:showbox pushes new .apk/workaround still working. they made the empty canvas visible..

### ISSUE THREAD

**Issue by psyde22** [Free-Software-for-Android/AdAway#519]
The app is ShowBox, I didn't write it on thr most obvious place because its in a grey area..and I have seen reactions very far stretched..

The blocker states its unresolvable, but as of today a very widespread app got this update and broke completely.. If there is anything I can do to help, contact me
Additional: the log cat file reports exception thrown because it checks for root, and has an implementation to check if a root escalated app hooks with intent to block the ads..the above DNS is their base, originating ad serving.
Additional 2: just got a TCP dump, has incomings from *inner-active.mobi (cdn1,cdn2,event,vserv and some others at the same domain level),and flurry.com, data.flurry.com 
TEMP SOLUTION whitelist cdn1/cdn2/event/wv/ of inner-active.mobi domain, img1/img2 of vserv.mobi, data.flurry.com , and SSL.gstatic.com , vshowsbox.RU
Then turn active connection off, I can verify WiFi, open the app, after it loads the thumbnails from cache (you must run it unblocked once ) then connect, it will function properly and without ads.
Until the dev updates it when he can, you can have a working ad block like this
Will update to include exception , selection of useful logs, how it targets each device..

The app creates a .HTML file in /storage/sdcard0 , I am pasting what I intercepted from the .VIEW intent: 

http://wv.inner-active.mobi/simpleM2M/ClientUpdateStatus?cn=Trendico_ShowBox_Tablet_Android&v=2_1_0-Android-4_0_2_7&ci=35601477994&s=4997916197627796046&cip=130-43-106-78&po=958&re=9&lt=0&cc=GR&acp=&pcp=

TYPE: null
CATEGORIES:
android.intent.category.BROWSABLE

FLAGS:
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP

EXTRAS:
EXTRA 1:
Class: java.lang.String
Key: com.android.browser.application_id. 
Value: com.android.htmlviewer

3 ACTIVITIES MATCH THIS INTENT:
Browser (com.android.browser - com.android.browser.BrowserActivity)
TubeMate (devian.tubemate.slide - devian.tubemate.slide.Main)
Web Page Clipper (for Evernote) (com.boatbrowser.free.addon.en - com.boatbrowser.enclipper.pro.MainActivity)

  
(I used HTML viewer and intercepted the action.intent.VIEW), this files URL is how it targets specifically every device, I will post a last paste from log cat about the method it uses, to check for a process with root escalation other than the owning the process hooks with intent to block the ad..)

Update: app XML preferences files, first it registers your cuid to RevMob (RevMob.xlm)

 Xml version='1.0' encoding='utf-8' standalone='yes' ?
map
<boolean name=registered value=true
/map

Next, iaCuidSettings.xml.  
  
  
Map
<string name=cuid 33360528459 /string
</map

Next, iaInstallSettings.XML and prefs.XML:

Map
boolean name=com.tdo.showbox install value=true
/map

Map
Int name="PREFS_FIRST_START" value1
Int name="PREFS_SELECTED_QUALITY" value=0
Int name="PREFS_PLAYER_MODE" value=2
Boolean name="PREFS_LOCATE" value=false
Int name="PREFS_UPDATE_PROGRESS" value=0
boolean name="PREFS_POST_FIRST_UPDATE" value=false
Int name="PREF_LIB_SUB_TAB" value=2131031418
String name="PREF_VERSION">2.5
Int name="PREFS_SELECTED_NEWS" value=2
Long name="PREFS_AD_DIALOG_LAST_TIME" value=1397163487117
Boolean name="PREFS_NEED_UPDATE" value=false
long name="PREF_UPDATE_TIME" value=1397157808000
/map

**Comment by 0-kaladin** [comment]
Whatever this is, is outside the scope of AdAway.
