### ISSUE TITLE
Huawei Ascend P7 - problem with HOSTS file?

### ISSUE THREAD

**Issue by YgrekIx** [Free-Software-for-Android/AdAway#527]
Hi.
I just notice that my brand new Huawei Ascend P7-L10 is immune to cure called Adaway :)
It seems that /system/ folder is read only. I was trying to change it to RW with ES file explorer but still can't edit hosts file.
Android KitKat 4.4.2

**Comment by 0-kaladin** [comment]
This isn't an adaway issue.  Adaway can't magically make your system writable.  Read the wiki for info on symlinking /data/data/hosts to /system/etc/hosts if your system still isn't writeable.
