### ISSUE TITLE
Failed on Xperia Z Ultra 4.4.4

### ISSUE THREAD

**Issue by skywinds5012** [Free-Software-for-Android/AdAway#529]
I just updated my Z Ultra to 4.4.4 last night, and I found that adaway can't moderate the hosts file. Also, the ad block in Luckypatcher could not moderate the hosts. I can view or write hosts in RE, and I tried to copied a hosts file made by adaway on other devices to Z Ultra, but it seems that no ad was blocked. What should I do now?

**Comment by 0-kaladin** [comment]
You can use adaway to add blocked urls or whitelist urls.  That's how you "moderate" the hosts.
