### ISSUE TITLE
When adding items to blacklist or whitelist, field is autocorrected by default keyboard

### ISSUE THREAD

**Issue by Gitoffthelawn** [Free-Software-for-Android/AdAway#541]
When adding items to blacklist or whitelist, the entry field is autocorrected by the default Android keyboard.  I think it is possible to set a flag for the entry field so that autocorrect is disabled.

Tested on KitKat.

**Comment by 0-kaladin** [comment]
blacklist was fixed above, whitelist was just fixed with this commit https://github.com/Free-Software-for-Android/AdAway/commit/6d0cc48f4ef4f28eecfa5665153f0a5b5b346961

**Comment by Gitoffthelawn** [comment]
Thanks!
