### ISSUE TITLE
Enhancement: Display Host Sources dates on smaller screens

### ISSUE THREAD

**Issue by Gitoffthelawn** [Free-Software-for-Android/AdAway#564]
On large screens, AdAway shows the dates of the Host Sources used for the current hosts file as well as the dates if the current update is applied.

On small screens, AdAway hides this information, and requires going to the separate Hosts Sources screen.

Perhaps, even on smaller screens, this information can be displayed on the main page.

**Comment by 0-kaladin** [comment]
Actually on smaller screens I'd like it to show that when rotated to landscape.  currently only shows the split screen on my tablet.

**Comment by Gitoffthelawn** [comment]
Although better than nothing, then users would have to rotate their devices (which could mean having to also turn on auto-rotate or something similar), every time they launch AdAway.  I would prefer something that always shows that important info on the main page.

I find the info important because it is the only indicator if it worth spending the time to reboot the device in order for the updates to take effect.  If only one small list has an update, it might not be worth it.  But if several lists have updates, it might be worth spending the time.

**Comment by 0-kaladin** [comment]
On such a small screen, i'm not going to try to cram in the hosts list.  Honestly, these don't need daily updates, they can be updated weekly. using the menu to check hosts sources as it stands is fine.  However what i just implemented is such that if you have a min of 600dp of width you will get the dual pane view.  So if you have that in portrait mode, on a tablet, then great, if you have to turn your phone landscape to get, oh well.   I'll mark this as closed once that has been committed.

**Comment by 0-kaladin** [comment]
Committed in https://github.com/Free-Software-for-Android/AdAway/commit/c8465836c63c59e9f9d456cdd897c83ede71315c
