### ISSUE TITLE
Blocking livefyre comments section

### ISSUE THREAD

**Issue by NicolaeEast** [Free-Software-for-Android/AdAway#607]
I am trying to enable adaway to allow a livefyre comments section on a website I regularly visit. I have gone through the dns scan and added the hosts which were accessed to my white list but I still can't view the comments section (unless I disable adaway... Which obviously I don't want to do. 

I'm running a Samsung Galaxy Note 4 sm-n910c rooted to lollipop 🍭 

Any help would be greatly appreciated!

**Comment by 0-kaladin** [comment]
If you provide the website in question so we don't have to hunt for one using livefyre comments then I will assist.  Since this issue was created months ago, if you don't respond in a couple weeks then I'll close out this issue as stale.

**Comment by NicolaeEast** [comment]
The site is Www.dailythunder.com

**Comment by 0-kaladin** [comment]
when i simply added:
``*livefyre.com``
to the whitelist it loaded the comments fine...
