### ISSUE TITLE
Version 3.0 loses all GUI color cues

### ISSUE THREAD

**Issue by Gitoffthelawn** [Free-Software-for-Android/AdAway#613]
Version 3.0 lost all color for the Enabled / Updates Available icons within the AdAway GUI.

These colors were very useful to tell at a glance if updates were available.  Yes, the text indicates it as well, but the color was a welcome cue.

Can the colors be reintroduced?

**Comment by 0-kaladin** [comment]
maybe to some degree...

**Comment by 0-kaladin** [comment]
Some color back with:
https://github.com/Free-Software-for-Android/AdAway/commit/45d43be2d92ad18abf4798fd0cbef9732235f30d
https://github.com/Free-Software-for-Android/AdAway/commit/480f4e0a738d6d86db6b43fb1a2e59a6ef260db3
