### ISSUE TITLE
Adaway blocks mobile links of news portal

### ISSUE THREAD

**Issue by mkkyah** [Free-Software-for-Android/AdAway#614]
Hi,
I fallow a news portal m.t24.com.tr on my phone. Using an app or directly chrome browser doesn't change the issue, the news links are blocked. I have tried to use Log DNS requests and added some links to whitelist, it helped a while but not too long. Maybe hosts are changing, maybe I add wrong ones, but I can't keep links working.
Is there a chance to ad-away work with this portal links?

**Comment by 0-kaladin** [comment]
The news links load fine for me with the default adaway hosts sources.  You didn't state whether you've added to the default list or not.  when clicking the news links I only see it making connections to api.twitter.com, facebook.com and fbcdn.net.  The good thing about the whitelist is you can use wild cards.  So if it is connecting to different fbcdn.net domains simply whitelist *.fbcdn.net

**Comment by mkkyah** [comment]
I get lots of connections listed. Can you please try 10-15 news links on that mobile page. Some facebook and twitter connections but lots of others loading my tcpdump list after doing that. I get definetly stucked on loading stage on mobile page of this portal.
Thanks for checking it.

**Comment by 0-kaladin** [comment]
I whitelisted
``secure*doubleclick.net`` and it worked. Unfortunately doubleclick.net is a large ad provider so whitelisting that may get you ads in other places.  Also they may load them from more than secure* so you might eventually have to whitelist *doubleclick.net which is even worse.  But it's your judgement call if their content is worth it to you.

**Comment by mkkyah** [comment]
*doubleclick.net alone didn't work for me. I have whitelisted a few more and it worked for now. I will try to uncheck some of them and try to find more specific ones.
thanks again.

**Comment by mkkyah** [comment]
I have spoken too soon, it's not working again. they probably change that addresses dynamically.

**Comment by 0-kaladin** [comment]
sure by there will only be so many.  
use also 
``*nr-data.net``
``*gemius.pl``
