### ISSUE TITLE
Sport1 app stopped working

### ISSUE THREAD

**Issue by Jodelinho** [Free-Software-for-Android/AdAway#615]
As the Sport1 app isn't mentioned in the problematic app list, i created this issue.
Please take a look at the hosts used by this app and add them to the list :)

**Comment by 0-kaladin** [comment]
You can follow this to resolve this on your own: https://github.com/Free-Software-for-Android/AdAway/wiki/Solutions

However in this case if you whitelist ``ad.71i.de`` the app then works for me.  I've added it to the wiki.
