### ISSUE TITLE
update host file loop

### ISSUE THREAD

**Issue by ka223** [Free-Software-for-Android/AdAway#618]
My adaway is currently in a loop downloading and updating the host file.

Deactivating is not available, I can only kill the app and restart.

Saw this before at version 3 ....

Android 4.4
adaway Version 3.0 from f-droid

After the switching to version 3.0 I can see another adaway entry at superSU with "AdAway [UID]", I can not allocate this.

**Comment by 0-kaladin** [comment]
Please clean install the latest version and try again.  If it doesn't work please post a logcat.  Will close this after 7 days no response.
