### ISSUE TITLE
AdAway Blocking Just-Eat App Transactions

### ISSUE THREAD

**Issue by sabret00the** [Free-Software-for-Android/AdAway#621]
When enabled I can't place an order, when I disable AdAway, orders go through just fine. I'm unsure of what to look for in order to whitelist, but it seems like a problem that probably is very bad.

**Comment by 0-kaladin** [comment]
Please follow this https://github.com/Free-Software-for-Android/AdAway/wiki/Solutions and the LogDNS section for how you can solve this.  I really don't want to attempt transactions myself to try to duplicate.  To be clear there is something in one of your hosts sources blocking one of the domains the application is using. You didn't specify whether you have added any sources.  But logging dns and figuring out which domain you need to whitelist is the only way to resolve.
