### ISSUE TITLE
Links blocked on Surfline.com

### ISSUE THREAD

**Issue by auburnham** [Free-Software-for-Android/AdAway#624]
Links do not work on Surfline.com when AdAway is enabled and using Chrome Mobile or Dolphin (i.e. Webkit).  However, links still work in Firefox Mobile (i.e. Gecko), or if I disable AdAway in Chrome Mobile or Dolphin.  Adding *surfline.com to the whitelist does not resolve the issue.  I have also logged DNS requests and added all that appeared to the whitelist, but that also did not resolve the issue. I have rebooted the phone after adding entries to the whitelist & applying, but the issue is still unresolved.  This is a new problem that just began a few days/weeks ago.  This issue appears to be most closely related to open bug #326, but may be similar to other bug reports #614, #442 & #353.

Version info:
Device: Sprint Samsung Note 4 (SM-N910P)
OS: Android 5.0.1 w/ root
AdAway 3.0 (52)
Chrome 42.0.2311.111

**Comment by 0-kaladin** [comment]
This isn't a bug but rather just figuring out what to whitelist.  When whitelisting you want to disable adaway to catch everything in the log.  For the surfline links to work you need to whitelist:
``*adroll.com``

**Comment by auburnham** [comment]
Thanks so much! I thought I had captured all of the required dns requests with the log feature, but that seems to have resolved the problem!

**Comment by auburnham** [comment]
I think I spoke too soon & pages were loading from cache, but after some time, links would no longer work on surfline.com, even with *.adroll.com on the whitelist. I did more testing today and I think the only required whitelist entry should be b.scorecardresearch.com. I hope this helps others.
