### ISSUE TITLE
MOAAB List From XDA Devs will not parse and/or merge

### ISSUE THREAD

**Issue by klusterfuk** [Free-Software-for-Android/AdAway#626]
I cannot get MOAAB lists to merge no matter what I do. Added to my hosts lists and the list fails to parse and merge every time.

The original post for the hosts file is here--
http://forum.xda-developers.com/showthread.php?t=1916098

The links I've tried that fail no matter what I do are--

http://adblock.mahakala.is/

http://moaab.tk/hosts.txt

**Comment by k2trf** [comment]
I also cannot merge the mahakala hosts list; it seems my 1GB RAM is too small to hold everything in ram and patch it.

http://moaab.tk/hosts.txt has worked for me though; it returns a 404 error now.

http://moaab.tk/hosts-2015-Mar-20-13:28:00.txt works in place for now; if you just go to http://moaab.tk/ you'll see it listed in the indexing. I have no idea why it was renamed to this; If I had to guess, they likely had an automatic refresh script running that had an issue renaming the file.

**Comment by Grossdm** [comment]
http://moaab.tk appears to be down.

**Comment by k2trf** [comment]
Indeed, and I can't find any page under the site through Wayback -- I've shoved my copy up to Dropbox for the time begin, in case you or others wanted it.

https://www.dropbox.com/s/uz351jy020xxl75/hosts?dl=0

Of course, sooner or later this list will be invalid, and I was not the origonal maintainer of this hosts file; I will likely move to a newer, updated one when that time comes. Likewise, I will eventually boot this off of the limited Dropbox space I have, especially once something newer & more updated becomes the defacto.

**Comment by 0-kaladin** [comment]
Please see my comment on #633 for why this is now closed.
