### ISSUE TITLE
Adaway crashes when parsing huge host file

### ISSUE THREAD

**Issue by siddharthasahu** [Free-Software-for-Android/AdAway#633]
I tried adding http://adblock.mahakala.is to the host files list. But adaway seems to be unable to parse and apply this huge host file. Adaway parses for some time and then crashes. Removing this makes the app work properly.

Adaway is probably running out of memory (1GB Moto G Falcon with CM 12.1). Is it possible to make Adaway parse the host files in a more intelligent way so that it does not crash?

Thanks for the awesome app.

**Comment by basitnadeem28** [comment]
Facing the same issue.

**Comment by 0-kaladin** [comment]
Note: this hosts file is probably counter productive but this is still a bug that it can't parse it.
See this for why you don't need such a large hosts file: https://github.com/sufficientlysecure/ad-away/wiki/Solutions

**Comment by 0-kaladin** [comment]
dupe to Issue 626

**Comment by 0-kaladin** [comment]
I've done a little more research.  As I mentioned above I believe using such a large hosts list is counter productive for a couple reasons.  
1. There are numerous reports on XDA forums of users who apply this hosts list via flashable zip that their device is now sluggish.  Probably once your hosts file gets a certain size it creates more overhead for the system to parse through it matching hosts then its worth.
2. In reality, your usage of your device, encounters hundreds of ad serving domains.  Not thousands.  You'd be best served to simply block the ad domains your device encounters in your usage.  The default hosts lists adaway provides tries to walk this line of providing the majority without going over board. This will keep your device running as efficiently as possible. 

All that being said the maintainer of this huge list has stated:
``So to be fail safe: MoaAB require atleast 2GB devices and i will not answer queries which are for less than those devices and/or At my will to answer. People are still complaining about Lag and Delayed experience ``
If he will not entertain queries for those who have <2GB ram on devices using this file then surely we can't blame adaway for not parsing it on a 1GB device that you have.  
To further test, this monstrosity does parse fine using adaway on my Galaxy S6 so there isn't a latent bug in adaway dealing with a huge file, it is simply a matter of device resources.

**Comment by siddharthasahu** [comment]
Reasonable arguments. Also, yes the default lists work fine for me :)
Thanks a lot for looking into this.
