### ISSUE TITLE
Tinfoil for Facebook broken since this 8/25 AM (US Central time)

### ISSUE THREAD

**Issue by jrod3737** [Free-Software-for-Android/AdAway#656]
Not sure if this is because of a new hosts file, and, if so not sure which line is causing the issue. The one that updated today is https://adaway.org/hosts.txt so I can only assume it's something on that file. When I disable adblocking the app performs normally. I added *faebook* to my white list and that did nothing.

**Comment by 0-kaladin** [comment]
Could have been any updates to any of the hosts sources but if you think it was an update to the adaway hosts file then add these as whitelist entries, re-apply adaway and reboot:
trackersimulator.org
eviltracker.net
do-not-tracker.org

If those don't solve the issue then follow this https://github.com/sufficientlysecure/ad-away/wiki/Solutions
Log dns requests and whitelist the hosts that show up there that Tinfoil may need to function.

**Comment by 0-kaladin** [comment]
Please follow this: https://github.com/Free-Software-for-Android/AdAway/wiki/Solutions and the Log DNS steps to figure out what to whitelist.  Post back here once found so we can add to the wiki to help others.
