### ISSUE TITLE
net::ERR_NETWORK_CHANGED

### ISSUE THREAD

**Issue by alexisju** [Free-Software-for-Android/AdAway#662]
Since i use Cyanogenmod 12.1 (Official Nightly Builds), i often have "net::ERR_NETWORK_CHANGED" error message when i open a link in background (ie : new tab with Firefox Mobile or using Ninja browser).

Returning default hosts solve this issue.

I guess it is more a cyanogenmod bug, but maybe it can be usefull for you to know that issue.

**Comment by 0-kaladin** [comment]
I had this too, then an updated to android system webview made it go away.  If you just google search for 'net::ERR_NETWORK_CHANGED' you'll see it happens all over regardless of adaway or not.  Something being blocked in the hosts file could be throwing the issue in firefox or ninja browser but that is why the whitelist functionality is built in.  Still i'm inclined to think adaway is not at the root of the problem since my issue went away after the webview update.

**Comment by Jason383** [comment]
Solved follow steps by step,

How To Fix ERR_NETWORK_CHANGED in Chrome: http://www.wiknix.com/how-to-fix-err_network_changed-in-chrome/

**Comment by rs372433** [comment]
So, here are the some guide to fix and solve this error ERR_NETWORK_CHANGED code problem.

How to fix Error ERR_NETWORK_CHANGED Code problem:-

1. Reinstall Network Adapter –
Go to the start menu
Search or go to the ‘RUN.’
Click on it and opens it
After that, Type this below the following command there
” hdwwiz.cpl “
Press Ok there
Expand network adapters, locate your network adapter name
Note down the name,
Right click on that adapter
Choose and click on the Uninstall option there
Reboot or restart your PC once
After restarting, reconnect to your network & test
If it isn’t installed, then download it from manufacturer website
After that, run it and reinstall it
After that, test it
After completing, close the tab
That’s it, done

2. Change the LAN settings –
o to the Google Chrome menu
Click on the Settings tab there
Click on the ‘Show Advanced Settings’ option there
Click on the “Change Proxy Settings” tab there
Now, go to the “LAN settings” and deselect the
” Use a Proxy server for your LAN “
After deselecting, close the tab there
That’s it, done

3. Flu..... Check out more at; Techinpost.com/[ERR_NETWORK_CHANGED](http://www.techinpost.com/fixed-error-err_network_changed-code-problem)
