### ISSUE TITLE
Read-only filesystems are not handled in any way

### ISSUE THREAD

**Issue by Kasalehlia** [Free-Software-for-Android/AdAway#664]
In my ROM, the '/system' partition is mounted read-only by default. AdAway does not detect this and instead reports a successful change. It would be nice if the app would do a remount (after asking) or at least show a notification and/or fail.

**Comment by 0-kaladin** [comment]
Can you post a logcat of adaway applying hosts file? It would not apply if file system is read only.

**Comment by Kasalehlia** [comment]
Looks like this issue was a permission problem in my ROM, after a system upgrade this behaviour is not reproducable.
