### ISSUE TITLE
Youtube history not updating

### ISSUE THREAD

**Issue by marcus1zuckerberg** [Free-Software-for-Android/AdAway#665]
When adaway is active my youtube history will not update.
I've tried whitelisting every host that pops up from using youtube and it has no effect.

**Comment by 0-kaladin** [comment]
It was discovered in the forums to whitelist: 
's.youtube.com'

**Comment by marcus1zuckerberg** [comment]
yeah I asked the same question there, someone posted that in reply.
thank god.

**Comment by davex2012** [comment]
I've the same problem with search history almost 3 months now. I did whitelisted *s.youtube.com / and *s.youtube.com* but shill don't work. Suggestion?

**Comment by marcus1zuckerberg** [comment]
Maybe you have another adblocker thats not whitelisting it.
That or try rebooting the phone, that's all I got.

**Comment by davex2012** [comment]
Marcus i don't have any other than Adaway. I've already did cache reboot etc.

**Comment by marcus1zuckerberg** [comment]
Do you have any additional hosts sources?
By default adaway has 4 so if you have any more than that one of them could contain another host causing the same problem.
Other than that im out of ideas.

**Comment by marcus1zuckerberg** [comment]
I just realized you said search history
If your watch history is working but search history isnt then it could be a different host altogether, not s.youtube
In that case youll have to look through the hosts files and trial and error youtube related hosts or see if anyone else has had the same problem as you on the internet. The adaway xda forum is where i eventually found someone who fixed the s.youtube problem so with a little bit of luck maybe you could find someone there who fixed your problem too.

**Comment by davex2012** [comment]
Problem still exists. I know s.youtube.com is in xda but don't fix in my case.

**Comment by xconclusion** [comment]
Davex ... make sure that after you add s.youtube.com, you need to apply the new settings by pressing on the "download files and apply ad blocking" button in the main page of AdAway ... it solved the problem for me

**Comment by davex2012** [comment]
Yes i did download and applied. My history is working but not my search history.

**Comment by zakzor** [comment]
I'm having the same problem as davex2012. Whitelisting "s.youtube.com" in AdAway solved my "watch history" issue but not the "search history".
I disabled AdAway for testing purposes, rebooted and nothing changed.
So... it's something else... If I find the solution I'll post it here.

**Comment by karanrajpal14** [comment]
@zakzor did you find a solution? I'm facing the same issue as well.

**Comment by zakzor** [comment]
@karanrajpal14 Yes but I can't remember what solved it. Sorry. It was a long time ago. But the whitelist is needed.
Try pausing history on YouTube on desktop and resume afterwards.

**Comment by karanrajpal14** [comment]
@zakzor will try it. Thank you!

**Comment by ssmohanv** [comment]
Thanks for the trick. Adding s.youtube.com in allowed list brings back watch history in YouTube. It also works with official and Vanced YouTube.

**Comment by Ezrakipkoech** [comment]
Go to magisk settings then configure denylist and mark YouTube ,worked for me 100%
