### ISSUE TITLE
Search for adware breaks app 

### ISSUE THREAD

**Issue by Gugiman** [Free-Software-for-Android/AdAway#666]
Just Touch for searching for adware (dont know how it is exactly called in english Version). On xperia z3 the app get always killed

**Comment by 0-kaladin** [comment]
Please uninstall adaway and install this dev build one to confirm it resolves the issue for you. 
https://www.androidfilehost.com/?fid=24052804347811295

**Comment by Gugiman** [comment]
Problem solved.

Keep up the good work!
