### ISSUE TITLE
Viggle no longer works when ad-blocking is enabled

### ISSUE THREAD

**Issue by kuyankee** [Free-Software-for-Android/AdAway#671]
The Viggle app does not work any longer when ad-blocking is enabled. This is only an issue since an app update on 9/16 to version 2.6.1.1. Thanks

**Comment by 0-kaladin** [comment]
Please read this.  https://github.com/Free-Software-for-Android/AdAway/wiki/Solutions
You simply need to disable adaway, run the log dns requests, use the app, and start whitelisting.  re-apply adaway and retest.  rinse, repeat.

**Comment by kuyankee** [comment]
Thank you and sorry for not researching this a bit more. I'll give this a
shot.

Thanks again!

**Comment by 0-kaladin** [comment]
I had a min on a test device where i don't mind installing things.  I did replicate Viggle just crashed when default hosts sources applied.  If you whitelist data.flurry.com it will open to the first screen.  I'll add this info to the wiki.
