### ISSUE TITLE
App does not install on Android <4.1

### ISSUE THREAD

**Issue by kollokollo** [Free-Software-for-Android/AdAway#676]
The app does not install on Android 3.2 and 4.01. Couldnt the app simply be compiled for Android 3.2 or lower? At least the installation of the hosts file should be possible also with older Android versions.

**Comment by 0-kaladin** [comment]
It isn't quite that simple.  Adaway 2.9.2 is the last version that supports <4.1.  You can still get that from here:  [AdAway 2.9.2] (https://www.androidfilehost.com/?fid=95747613655045621)
