### ISSUE TITLE
IPv6 Option

### ISSUE THREAD

**Issue by Gitoffthelawn** [Free-Software-for-Android/AdAway#680]
Using the IPv6 option, by necessity, will double the size of one's *hosts* file.

How can users determine if they need to enable that option?

**Comment by 0-kaladin** [comment]
not easily but it causes no harm.  it's really for future proofing.  I haven't noticed any ads coming over ipv6 but if you have a site blacklisted and have identified you are still getting ads from it then they must be coming from ipv6 so i'd enable it.  There will never be a magic button to press to recommend using the IPv6 option.

**Comment by Gitoffthelawn** [comment]
Related: https://github.com/StevenBlack/hosts/issues/47

**Comment by 0-kaladin** [comment]
Well I guess when I put it in for future proofing, the future came sooner than I thought.

**Comment by Gitoffthelawn** [comment]
@0-kaladin It seems to do that. ;-)

**Comment by Goliath0** [comment]
What is with ipv4only,arpa?
