### ISSUE TITLE
CyanogenMod moving from BusyBox to ToyBox

### ISSUE THREAD

**Issue by mmogithub** [Free-Software-for-Android/AdAway#681]
Recently CyanogenMod custom rom has moved from Busybox to ToyBox (at least in CM13 - Marshmallow).
I'm afraid they're already moving and it is not completed yet.
But the key question is AdAway is not working properly for root acces in CM13.

Would it be possible to adapt to this new scenario??

**Comment by 0-kaladin** [comment]
AdAway is working fine on nexus6p and nexus 9 marshmallow. Also doesn't require busybox so doesn't matter which busybox they use. Can you elaborate on what isn't working exactly on cm13?

**Comment by mmogithub** [comment]
I got an error trying to update host file

https://www.dropbox.com/s/ma9pfpz2t1eiuc9/Screenshot%20%2817%20nov.%202015%2017_54_24%29.png?dl=0

The log is here: https://www.dropbox.com/s/tg1uaigfrlsgoeq/How%20to%20use%20the%20Public%20folder.rtf?dl=0

For example:

11-17 17:41:44.827 I/SuControllerImpl(999): Got change
11-17 17:41:44.828 D/su      (17188): sending code
11-17 17:41:44.828 D/su      (17188): child exited
11-17 17:41:44.828 D/su      (17186): client exited 0
11-17 17:41:44.852 E/AdAway  (16724): Exception!
11-17 17:41:44.852 E/AdAway  (16724): org.adaway.util.CommandException
11-17 17:41:44.852 E/AdAway  (16724): 	at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:176)
11-17 17:41:44.852 E/AdAway  (16724): 	at org.adaway.service.ApplyService.apply(ApplyService.java:420)
11-17 17:41:44.852 E/AdAway  (16724): 	at org.adaway.service.ApplyService.doWakefulWork(ApplyService.java:100)
11-17 17:41:44.852 E/AdAway  (16724): 	at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:100)
11-17 17:41:44.852 E/AdAway  (16724): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
11-17 17:41:44.852 E/AdAway  (16724): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 17:41:44.852 E/AdAway  (16724): 	at android.os.Looper.loop(Looper.java:148)
11-17 17:41:44.852 E/AdAway  (16724): 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-17 17:41:44.879 D/su      (17199): su invoked.

Regards

**Comment by julianxhokaxhiu** [comment]
+1 on CM13

**Comment by 0-kaladin** [comment]
Adaway requires R/W access to system or for you to change the hosts target to somewhere it can write to, like /data/hosts and create a symlink to /system/etc/hosts. 
This isn't a Adaway issue, rather you don't have the basic requirements met for it to work.

**Comment by julianxhokaxhiu** [comment]
Could this be related to the fact they're not using Busybox anymore?
I see no relation on this, but it's the only thing that's different from CM12.1

**Comment by mmogithub** [comment]
Dear 0-kaladin,

The question is IT WAS working one week ago in cm13.
They (cm) have changed something about root access since 15/11.
Now it does not work.

You can claim it is not adaway fault. And probably you are right. But
probably in any cm based rom it will not work. That is too many
installations. Be ready for tons of issue reports.

I was trying to help anticipating that. Cm13 is not nightly based yet.

Saludos

**Comment by julianxhokaxhiu** [comment]
@mmogithub I think it will resolve itself. See this patch http://review.cyanogenmod.org/#/c/119929/

**Comment by robin-vandaele** [comment]
Hasn't been fixed yet..

**Comment by 0-kaladin** [comment]
Not having R/W access to edit the hosts file has never been an Adaway issue and never will be.  Get R/W or employ one of the many workarounds (like a symlink), or even the new systemless root methods you can mount -o bind with /su/etc/hosts to /system/etc/hosts so Adaway never touches/modifies system.  
All of these are outside of the app,  you as the user, meet the prereq's for a modified host file (whether directly on system, through a symlink, or a mount bind command and adaway will diligently keep it updated from your sources.
