### ISSUE TITLE
Failed(6.0 MM)

### ISSUE THREAD

**Issue by nazmirul** [Free-Software-for-Android/AdAway#684]
Copy Failed
"copying of hosts file failed"

i having this issue ,already try to change target hosts file still cannot.

device oneplus one
rom: [Unofficial CyanogenMod 13.0 with 3.4.0 kernel](http://forum.xda-developers.com/oneplus-one/orig-development/rom-kernel-unofficial-cyanogenmod-13-0-t3242700)

**Comment by 0-kaladin** [comment]
Known issue with CM.  Your best bet is to follow your device forum on xda and post/read regarding inability to write to system.  There are current workarounds, like you can manually remount your system to rw and copy the hosts file for a one time update.
