### ISSUE TITLE
"Copy Failed" error

### ISSUE THREAD

**Issue by TedVoltolina** [Free-Software-for-Android/AdAway#685]
Device: Nexus 5X
Android: 6.0
Builds: MDB08I, MDB08L, MDB08M
AdAway: 3.1
SuperSU: 2.52

Details:

I've always been able to use AdAway without issue on my Nexus 5 and Nexus 9.  It's up and running just fine on my N9.  I had it running on my N5X until earlier today, when I tried upgrading to MDB08M.

I rooted MDB08M using Nexus Root Toolkit 2.0.7 and it went just fine.  Installed AdAway using the APK, not F-Droid.  The source files download, it applies and builds the hosts file, but then gives me this error message:

Copy failed.  Copying of hosts file failed!  Please read Help for more information.

I wasn't able to find anything helpful in the Help file.  Is anyone else having this issue?

![screenshot_20151119-223910](https://cloud.githubusercontent.com/assets/15936471/11291557/ce764798-8f0f-11e5-9fc9-04ef3cd5c763.png)

**Comment by 0-kaladin** [comment]
This means you don't have r/w access to system.  I'd post the the toolkit thread or your device forum on xda asking if anyone has r/w to system and how they rooted.  Could be issue with the toolkit.  I have systemless root running on Nexus 9, 5X, and 6p with adaway working fine.

**Comment by ethan1701** [comment]
We're you ever able to resolve this? 
I have the same exact problem on a nexus 6p running Android 7.

**Comment by TedVoltolina** [comment]
I think it was a problem with the way that version of Nexus Root Toolkit was rooting. It was fixed with subsequent versions.

I haven't used it in a long time though. I eventually decided to unroot and just use Adguard instead of Adaway. I haven't had any problems using it. It works great, I don't have to worry about hacking my device to apply each monthly update, and I can use Android Pay.

If you only root to block ads, I'd highly recommend using Adguard instead. It's not on the Play Store -- you have to download it from their site. But once you do, it will auto update.

**Comment by ethan1701** [comment]
Apparently it's an issue with systemless root, while AdAway needs access to /system.
I found this thread: https://www.reddit.com/r/Nexus6P/comments/4k0ghq/adaway/
which lead me to the AdAway thread on XDA: http://forum.xda-developers.com/showthread.php?t=2190753
I downloaded the [Flash for systemless hosts file] zip file, and flashed it with TWRP. After that, I successfully got AdAway to apply the changes, and ads are gone,
