### ISSUE TITLE
Conection Issues with Adaway enabled

### ISSUE THREAD

**Issue by babywin** [Free-Software-for-Android/AdAway#686]
Hi guys. I've experiencied constant and periodical conection issues with Adaway enabled.
If I disable the wi fi and reconect the problem is solved for a new lapse.
Is so anoying do this every 20 or 30 minutes.

**Comment by 0-kaladin** [comment]
You really have to troubleshoot this yourself.  Potentially something in the hosts file is blocking something needed for this "connection" that you don't really specify what it is.  Whatever the connection is, see if it has any entries in the hosts files, they are in /system/etc/hosts as default.
