### ISSUE TITLE
whitelist not working

### ISSUE THREAD

**Issue by jeffshead** [Free-Software-for-Android/AdAway#687]
For the past week, streaming from two sites as been blocked by AdAway.

I can no longer stream from the two URL's below:

http://player.listenlive.co/29591
http://player.listenlive.co/26491/

I have used the 'Log DNS Requests' feature and added the following to the whitelist but streaming is still blocked:

player.listenlive.co
*player.listenlive.co*
playerservices.live.streamtheworld.com
api.listenlive.co
connect.facebook.net
fonts.gstatic.com
playercdn.listenlive.co
s-static.ak.facebook.com
scontetnt-iad3-1.xx.fbcdn.net
static.ak.facebook.com
static.xxfbcdn.net
www.facebook.com

I did disable, reboot, enable, reboot after adding the URL's above to the whitelist but streaming still fails until I disable AdAway.

My phone is an HTC M8. Up until a week ago, I could stream from both URL's with AdAway enabled.

Please help me figure out which entry in the hosts file is keeping the steaming player from loading.

**Comment by jeffshead** [comment]
What a pain in the @ss! I had to copy the HOSTS file to a PC and manually find the bad entry, listed below, because 'Log DNS Requests' did not work!

127.0.0.1 imasdk.googleapis.com

The domain above has to be whitelisted if you stream audio from sites that utilize Triton Digital (listenlive.co, streamtheworld.com).

**Comment by IDKwhattoputhere** [comment]
How about you watch your profanity and report this to the maintainers of the respective hosts file next time?
http://hosts-file.net/default.asp?s=imasdk.googleapis.com
That way all users of Adaway can profit from your findings.

**Comment by jeffshead** [comment]
How about you kiss my @ss, IDKwhattoputhere!

**Comment by IDKwhattoputhere** [comment]
Sure showing maturity here. You have a great future ahead of you with that attitude.

**Comment by jeffshead** [comment]
Maturity? That’s really funny coming from someone who thinks it’s their moral obligation to chastise someone for deliberately misspelling a “profane” word as you put it. This is my last response but I will tell you that if you want to continue this discussion in person, I will provide an address, date and time where we can meet.

**Comment by IDKwhattoputhere** [comment]
Please, just stop. You are embarrassing yourself. No one would be interested in meeting a person like you.

**Comment by Techman-** [comment]
@0-kaladin Please lock this thread
