### ISSUE TITLE
adaway 3.1

### ISSUE THREAD

**Issue by laffreux99** [Free-Software-for-Android/AdAway#689]
Doesn't working un 3g connections, ans I can'fix it ...

**Comment by 0-kaladin** [comment]
the only thing that would make it not work on 3g is if you had a proxy configured on your 3g apn settings.  ensure you don't have a proxy in your APN.

**Comment by laffreux99** [comment]
Thanks, I have cancelled the proxy in my 3g setting and Adaway works correctly ...

1-dic-2015 ha scritto:

the only thing that would make it not work on 3g is if you had a proxy configured on your 3g apn settings. ensure you don't have a proxy in your APN.

—
Reply to this email directly or view it on GitHub. 


-- Inviato dal mio cellulare Android con K-@ Mail.
