### ISSUE TITLE
Android 6 remount /system

### ISSUE THREAD

**Issue by flecno** [Free-Software-for-Android/AdAway#691]
Hey,

I have upgrade to cm13 which brings android 6 on my smartphone. Now I can't replace my hosts file anymore.

I debuged the remount part of AdAway. There are four commands which are executed but nothing will remount /system with write permissions.

1. `busybox mount -o remount,rw /dev/block/platform/msm_sdcc.1/by-name/system /system`
-> exit 0 but already mounted ro

2. `toolbox mount -o remount,rw /dev/block/platform/msm_sdcc.1/by-name/system /system`
-> exit 255 "mount: no such tool"

3. `mount -o remount,rw /dev/block/platform/msm_sdcc.1/by-name/system /system`
-> exit 1 "mount: '/dev/block/platform/msm_sdcc.1/by-name/system'->'/system': Permission denied" (I was really root `uid=0(root)`)

4. `/system/bin/toolbox mount -o remount,rw /dev/block/platform/msm_sdcc.1/by-name/system /system`
-> exit 255 "mount: no such tool"

I think this is an new issue with android 6. I found some other people who reports this problem (eg. http://forum.xda-developers.com/nexus-6/help/mount-o-remount-rw-mount-read-file-t3154703). Anyone has an idea how to get AdAway working now?

**Comment by 0-kaladin** [comment]
This is an issue with cm13, not android 6.  I don't follow CM much anymore but if you google it seems they've had issues with write access to system.  As a workaround you should boot to recovery and see if you can create a symlink to /system/etc/hosts from /data/hosts or /data/data/hosts
like ln -s /system/etc/hosts /data/hosts
then reboot and go into adaway, preferences and change the target hosts file to be /data/hosts and see if it can apply then.

**Comment by flecno** [comment]
Oh year.. After upgrade from cm-13.0-20151127-NIGHTLY to  cm-13.0-20151203-NIGHTLY it works for me!
