### ISSUE TITLE
Webserver not running on stock rooted Touchwiz KK 4.4.2

### ISSUE THREAD

**Issue by CrescendoFang** [Free-Software-for-Android/AdAway#692]
Unable to enable the webserver on my Tab S (SM-T705) & Note 3 (SM-N900) whatever I do...
But strangely, it works perfectly with my Note 8.0 (GT-N5100)...

All runnung stock rooted latest 4.4.2 Touchwiz ROM with AdAway v3.1...

And where the log file located? Or I have to grab the debug log from logcat?

**Comment by 0-kaladin** [comment]
Yes please post a debug log from logcat so we can see why the webserver isn't starting.

**Comment by 0-kaladin** [comment]
also confirm latest version of adaway from f-droid.
