### ISSUE TITLE
Updates? 

### ISSUE THREAD

**Issue by Shtiff** [Free-Software-for-Android/AdAway#693]
App is not updating automatically. Every time I go back to the app it always says disabled. All correct boxes are checked for automatic updates. Please advise

**Comment by 0-kaladin** [comment]
if you go back to app and it says disabled, then that means something is changing your /system/etc/hosts file underneath adaway or adaway is not able to write to it.  I can't really help you solving that since it isn't related to adaway.  check your rom and rooted properly.

**Comment by Shtiff** [comment]
I'm pretty sure I'm rooted correctly. Please see attached for file you were
referring to. Would having multiple ad blockers interfere?

**Comment by 0-kaladin** [comment]
if one of the adblockers is also modifying the hosts file, then yes.  use one.

**Comment by Shtiff** [comment]
I think it is because this is after reapplying adaway.
