### ISSUE TITLE
Please block 'decide.mixpanel.com'

### ISSUE THREAD

**Issue by ericjhwang** [Free-Software-for-Android/AdAway#696]
Your adblocker blocks-
127.0.0.1 mixpanel.com

127.0.0.1 www.mixpanel.com

127.0.0.1 api.mixpanel.com

Please add 'decide.mixpanel.com' to the list of Mixpanel URLs that have been remapped. Thanks!

**Comment by 0-kaladin** [comment]
@dschuermann for fyi.

**Comment by dschuermann** [comment]
'decide.mixpanel.com' is already in http://hosts-file.net/ad_servers.txt
