### ISSUE TITLE
defective rows

### ISSUE THREAD

**Issue by TheCatcher** [Free-Software-for-Android/AdAway#698]
Lock at the screenshot
![screen_07122015123013](https://cloud.githubusercontent.com/assets/3627565/11761632/3afdd0fe-a0ca-11e5-84b2-88e574c88c55.png)

**Comment by 0-kaladin** [comment]
Nothing defective.  Those are valid, blocked domains.  You can find some in this file 
http://hosts-file.net/ad_servers.txt
