### ISSUE TITLE
Can not install version 3.1

### ISSUE THREAD

**Issue by oflodac** [Free-Software-for-Android/AdAway#699]
I installed version 2 working perfectly, when I try to install version 3.1 to my phone (Huawei G Play G735-L23) is rejecting the installation, even if I uninstall the the old version, is there a solution?. By the way, my android version is 4.4

**Comment by 0-kaladin** [comment]
Have you enabled unknown sources? what is the exact error you get?  I can assure you this is not an Adaway issue but rather something/some setting on your device.

**Comment by oflodac** [comment]
Thanks for your answer. Look at the attachments with screenshots:
1) In this screenshot, you can see that version 2.0 is installed, working perfectly.

![screenshot01](https://cloud.githubusercontent.com/assets/12475321/11873084/6491e004-a49e-11e5-9ce8-8f9d26a6f7dd.jpeg)

2) In this screenshot, you can see unknown sources ("fuentes desconocidas" in spanish) is enabled. By the way, this is the only way I can install apps out of google play.

![screenshot02](https://cloud.githubusercontent.com/assets/12475321/11873127/9b14594a-a49e-11e5-85e1-966076350a1f.jpeg)

3) In this screenshot, you can see I trying to install adaway version 3.1

![screenshot03](https://cloud.githubusercontent.com/assets/12475321/11873140/aef9f6c2-a49e-11e5-83dd-4dee929120d6.jpeg)

4) In this screenshot, no success !!

![screenshot04](https://cloud.githubusercontent.com/assets/12475321/11873160/bea83c1e-a49e-11e5-8266-068e4a67e4f3.jpeg)

I already tried with other adaway apk sources (version 3.1), same problem, my phone rejects the instalation.
As I informed before, version 2 is working perfectly, so I believe there is no any other setting enabled that rejects the installation.
What else can I do?

**Comment by 0-kaladin** [comment]
are you sure you fully uninstalled the one from the play store?

**Comment by oflodac** [comment]
Thanks, I had success now, the difference was that removed the cache, data and force detention before I uninstalled version 2. Now version 3.1 is working. Thanks again :)
