### ISSUE TITLE
adaway

### ISSUE THREAD

**Issue by lynxster** [Free-Software-for-Android/AdAway#701]
Cant seem to unblock realtor.com unless I disable adaway I tried adding to whitelist w and w/o the * and ?....any help would be greatly appreciated. ..

**Comment by 0-kaladin** [comment]
that would work *realtor.com in a whitelist will whitelist it.  are you sure there isn't some other domain you need to whitelist?  what are you trying to do?

**Comment by lynxster** [comment]
I have tried that u can go to site but try typing in a city or state when u
hit search nothing happens ...the site normally starts putting in the city
-state as u type I dont know how to find if its something else I need to
add to whitelist...I have to disable adaway..restart then all works well...
just started about 4-5 days ago...i appreciate any help ...thank you

**Comment by 0-kaladin** [comment]
You need to whitelist assets.adobedtm.com
