### ISSUE TITLE
Freeletics stops displaying ANY information after adaway is enabled

### ISSUE THREAD

**Issue by stephanemaarek** [Free-Software-for-Android/AdAway#707]
Here is a link to the app:
https://play.google.com/store/apps/details?id=com.freeletics.lite&hl=en

I tried enabling DNS logging to see if anything went wrong but no luck...
Can you please confirm the issue ? 
Thanks a LOT for your help

**Comment by 0-kaladin** [comment]
I was going to help but after installing app it needed me to create a profile and login to do anything.  which i'm not willing to do.  
However, you can confirm the issue yourself.  Disable adaway.  Still have issue?  disable individual host sources to see if you can narrow down or follow https://github.com/Free-Software-for-Android/AdAway/wiki/LogDNS in particular you are looking to whitelist something so follow the steps that mention whitelisting.

**Comment by stephanemaarek** [comment]
Hi,

Can you please close this issue?
It turned out it was a bad circumstances play as freeletics was also having
server issues. Coincidences.... Everything's been working well since!
