### ISSUE TITLE
From 2.3 to 3.1 installation error

### ISSUE THREAD

**Issue by apollonaute** [Free-Software-for-Android/AdAway#708]
I've got exactly the same problem as described here https://github.com/Free-Software-for-Android/AdAway/issues/699
But I can't figure why I can't install 3.1 even with reinstallation of 2.3, clean cache.... And uninstallation. Any idea?

Android 5.1.1 with CyanogenOS 12.1 on my OnePlus One.

**Comment by 0-kaladin** [comment]
how did you clean cache?  look in your data folder for any adaway stuff and manually delete.

**Comment by apollonaute** [comment]
First with the 'app menu' (Settings>Apps>AdAway) then uninstalling it, then finally by searching with ES File Explorer and deleting every single 'adaway' file that I've found.

**Comment by apollonaute** [comment]
Any help? Thank's!

**Comment by 0-kaladin** [comment]
and you tried what the guy in 699 did?  go to settings , apps, adaway with the 2.x installed.  click force stop, clear cache, clear data.  then uninstall. Then i'd reboot the phone and after booting try installing the new version.  Other than that I can't really tell you.  Since you are on cyanogen I assume you have a non-stock recovery so maybe during that reboot go into twrp and also wipe cache/dalvik.

**Comment by apollonaute** [comment]
That is exactly what I've done! Even Cache/Dalvik wipe!
Sorry about that but it's still impossible to install the new 3.1 APK....
Leave this issue open, I will investigate again...

2016-01-13 15:16 GMT+01:00 0-kaladin <notifications@github.com>:

**Comment by bluespy** [comment]
Say, what are the installation error message saying?
Investigating in logcat might help in this case.

**Comment by apollonaute** [comment]
In French, something like "Installation is impossible".
Please find the logcat, it seems to be a signature problem. 
https://0bin.net/paste/bJU7BSpd9JCoXVFm#1zmpt7SQmqdBd6QTzBRG0vZse241Ea6d-lBz4m16mbi

**Package org.adaway signatures do not match the previously installed version; ignoring!**

**Comment by apollonaute** [comment]
Problem solved!
 After searching on Stackoverflow, I've found a "simple" solution : http://stackoverflow.com/a/20084044/5773754

Finally, the old version app didn't uninstall completely. And a trace was still here (with an old app signature). And that blocked the new app installation. 

So, to solve this issue: Settings > Apps > All Apps tab, then scroll at the very end and you should find "org.adaway" withe the label "Not installed". Select it, it open the app parameters. Go to the Settings (the three dots) and "Uninstall for all users". Install properly the new version of your app!

Thank a lot for everything and for the advice (clean cache, logcat, ...). See you!
