### ISSUE TITLE
Typo in german translation

### ISSUE THREAD

**Issue by Guillane** [Free-Software-for-Android/AdAway#714]
Settings -> Activate IPv6 has a typo in the german translation

"IPv6 akitivieren" should be "IPv6 aktivieren"

**Comment by Primokorn** [comment]
We have "IPv6 aktivieren" in the [strings](https://github.com/Free-Software-for-Android/AdAway/blob/master/AdAway/src/main/res/values-de/strings.xml).

> <string name="pref_enable_ipv6">IPv6 aktivieren</string>

**Comment by 0-kaladin** [comment]
I'll post a 3.1.1 version before android N that will include all updated translations.
