### ISSUE TITLE
Publish it on Google Play

### ISSUE THREAD

**Issue by sssemil** [Free-Software-for-Android/AdAway#720]
It is possible to rename app, remove all preinstalled sources for hosts, rename all stuff like "apply ad blocking" to something without word ad like "apply web sites filtering" etc. Like here - https://play.google.com/store/apps/details?id=sssemil.com.hostsaway

**Comment by dschuermann** [comment]
It is also possible to publish AdAway exactly like it is. Google has no human verification process like Apple. But Google will probably delete it when many people start using it. At least that is how I understand the situation.

**Comment by sssemil** [comment]
Are they removing it because it blocks ads or because it interferes with other apps?(I know it's because of ad blocking but I mean "official" reason)

**Comment by dschuermann** [comment]
4.4 in https://play.google.com/about/developer-distribution-agreement.html

**Comment by sssemil** [comment]
Thanks. Hmm, it says "in an unauthorized manner". Does it mean if we show some dialog like " this app will do bla bla bla.." then app will fit 4.4?

**Comment by dschuermann** [comment]
No :) It means that you are not allowed to interfere with other services in an unauthorized manner in regards to the service's policies.
Sry, but this whole discussion is not worth it, believe me. Google acts in totally unpredictable ways regarding their Google Play policies. I had AdAway in Google Play for over 3 years (as far as I remember) and then at one point they decided to remove every ad blocker.
You will find stories regarding other issues, like 
* http://andrewpearson.org/?p=681
* http://techdissected.com/google/google-play-accounts-being-banned-for-no-reason/
* https://www.reddit.com/r/Android/comments/2hywu9/google_play_only_one_strike_is_needed_to_ruin_you/
* http://phandroid.com/2015/01/04/play-store-developer-policies/

By the way: Besides AdAway's removal, I also got emails from Google that forced me to remove PayPal and Flattr donation capability. Only Google Play is allowed as payment inside apps (even for donations).

Just to make this clear: I don't have any objections against putting a version into Google Play as long as it's on your responsibility ;)

**Comment by sssemil** [comment]
Ouch. I think I'd better unpublish it then.

**Comment by 0-kaladin** [comment]
Looks like might be able to get it published
http://techcrunch.com/2016/02/09/google-reverses-its-decision-to-ban-ad-blocking-apps-from-the-google-play-store/

**Comment by dschuermann** [comment]
I made an appeal to Google, citing the article, we'll see what they answer...

**Comment by SecUpwN** [comment]
>Google acts in totally unpredictable ways regarding their Google Play policies

@dschuermann, you're absolutely right! If you ask me, Google does not deserve your great app. You've done the right thing by publishing it on F-Droid, consider adding a [NoGooglePlay statement](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-why-wont-you-upload-your-app-to-the-google-play-store) like we did.

**Comment by dschuermann** [comment]
Nope :)

> Hi Dominik,
> 
> Thank you for your note. Please be advised that the functionality of your
> app makes it ineligible for reinstatement, as it is still in violation of
> Google Play's policies. Specifically, the Developer Distribution Agreement
> <https://play.google.com/intl/ALL_us/about/developer-distribution-agreement.html>
> 4.4:
> 
>    - 4.4 *Prohibited Actions.* You agree that you will not engage in any
>    activity with the Store, including the development or distribution of
>    Products, that interferes with, disrupts, damages, or accesses in an
>    unauthorized manner the devices, servers, networks, or other properties or
>    services of any third party including, but not limited to, Android
>    users, Google or any mobile network operator. You may not use customer
>    information obtained from the Store to sell or distribute Products outside
>    of the Store.
> 
> Based upon how we understand your app works, it blocks policy compliant
> functionality in third party apps distributed on the Store. Our
> understanding of the other app you've mentioned, is that it integrates with
> an API provided by the companion app only, and doesn't disrupt other third
> party app functionality.
> We regret the confusion any misleading third party external articles may
> have conveyed regarding apps in this segment, but would like to take the
> time to re-iterate the position.
> We appreciate your taking the time to contact us and giving us opportunity
> to clarify.
> 
> Regards,
> The Google Play Team
