### ISSUE TITLE
Inclusion of Steven Black's HOSTS file?

### ISSUE THREAD

**Issue by Gitoffthelawn** [Free-Software-for-Android/AdAway#724]
Would it be a good or bad idea for you to include Steven Black's HOSTS file as a list in AdAway?

See: https://github.com/StevenBlack/hosts/issues/83

**Comment by dschuermann** [comment]
See https://github.com/Free-Software-for-Android/AdAway/issues/723

**Comment by Gitoffthelawn** [comment]
LOL... 4 days ago... missed it by *that* much...

Thanks!
