### ISSUE TITLE
Add hosts.txt of YousList

### ISSUE THREAD

**Issue by yous** [Free-Software-for-Android/AdAway#727]
Hi, I'm an author of [YousList](https://github.com/yous/YousList), and I recently created `hosts.txt` based on `youslist.txt` which already have been used in [uBlock Origin](https://github.com/gorhill/uBlock) as a Korean third-party filter. I would appreciate it if you add the following URL to https://github.com/Free-Software-for-Android/AdAway/wiki/HostsSources.

```
https://github.com/yous/YousList/raw/master/hosts.txt
```

**Comment by dschuermann** [comment]
done

**Comment by yous** [comment]
Thanks! Additionally, the file is under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/).

**Comment by dschuermann** [comment]
k
