### ISSUE TITLE
Text field on adding site to blacklist isn't set as URL field so keyboard autocorrect is enabled (Android App) 

### ISSUE THREAD

**Issue by abqnm** [Free-Software-for-Android/AdAway#728]
In the add dialog for the whitelist, the field is defined such that autocorrect is not activated on the keyboard since you're entering a url. On the add dialog for the blacklist, however, the text field is defined as just a normal text field, which tells the keyboard autocorrect is allowed, making it difficult to enter URLs because the keyboard is trying to correct the entered text.

**Comment by 0-kaladin** [comment]
Can you confirm the adaway version you are using?  only the redirection field has that issue in latest builds but has been fixed in source already.

**Comment by abqnm** [comment]
My apologies for forgetting the version. I'm running 3.1 from F-Droid.

**Comment by 0-kaladin** [comment]
Grab the dev build here you shouldn't have that issue.  Let me know.  Will be fixed in 3.1.1
