### ISSUE TITLE
Add F-Droid button to repository README

### ISSUE THREAD

**Issue by SecUpwN** [Free-Software-for-Android/AdAway#730]
Good evening @Free-Software-for-Android, thanks for still developing this wonderful app! Please add this F-Droid button to the `README` below the word `AdAway` so that more developers will have a look. :)

[![F-Droid](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Get_it_on_F-Droid.svg/320px-Get_it_on_F-Droid.svg.png)](https://f-droid.org/repository/browse/?fdid=org.adaway "AdAway on F-Droid")

Code to copy and paste into your `README` (if you're *really* lazy, tell me and I will open a pull request):

```
[![F-Droid](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Get_it_on_F-Droid.svg/320px-Get_it_on_F-Droid.svg.png)](https://f-droid.org/repository/browse/?fdid=org.adaway "AdAway on F-Droid")
```

**Comment by 0-kaladin** [comment]
done.
