### ISSUE TITLE
Change default permission for hosts file

### ISSUE THREAD

**Issue by Eselter** [Free-Software-for-Android/AdAway#731]
According to this:
http://forum.xda-developers.com/android/help/fix-android-scroll-lag-caused-host-file-t3286993
Please change default permisson to hosts file to rw-r----- (0604) this really help.
Or remember last permission.

**Comment by 0-kaladin** [comment]
This makes no real sense.  I feel like if anything there is a bug somewhere else in these people's android and this is some workaround they oddly discovered.  def do not want to change hosts file perm from what stock android has it.
