### ISSUE TITLE
Yoast.com being blocked

### ISSUE THREAD

**Issue by jdevalk** [Free-Software-for-Android/AdAway#735]
Hi, I'm Joost de Valk, CEO of Yoast, which runs yoast.com.

I was shocked to find out today that we're being blocked because of being added on [this list](http://hosts-file.net/ad_servers.txt). Yoast.com serves no ads, it doesn't even have ads. In fact, we're a company dedicated to open source, building a WordPress plugin called Yoast SEO and employing several WordPress core developers... Please get us unblocked ASAP.

**Comment by dschuermann** [comment]
Please contact the maintainer of this list, we can not help you with that.
