### ISSUE TITLE
symlinking hostfile don't work on android N preview

### ISSUE THREAD

**Issue by schorsch3000** [Free-Software-for-Android/AdAway#736]
Hi,
i'm running the N preview on an Nexus 6.
It's rooted with the latest CD-AutoRoot.
While activating the hostfile, the message apply_symlink_missing pop up.
i choose yes and the message apply_symlink_fail pops up.
before the N preview everything was fine.
I'm aware that this is somewhat less Information, but i don't know what could be needed.
I'm happily do what i can to help you out here, just ask.

**Comment by buntspexxxxt** [comment]
Same problem here on Nexus 5x. This is the logcat:

`03-15 11:20:40.719 15059 15059 W IntentService[A: type=1400 audit(0.0:835): avc: denied { read } for name="RootToolsMounts" dev="dm-0" ino=752195 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
03-15 11:20:40.725 14775 15059 E RootCommands: Exception
03-15 11:20:40.725 14775 15059 E RootCommands: java.io.FileNotFoundException: /data/local/RootToolsMounts (Permission denied)
03-15 11:20:40.725 14775 15059 E RootCommands:  at java.io.FileInputStream.open(Native Method)
03-15 11:20:40.725 14775 15059 E RootCommands:  at java.io.FileInputStream.<init>(FileInputStream.java:146)
03-15 11:20:40.725 14775 15059 E RootCommands:  at java.io.FileInputStream.<init>(FileInputStream.java:99)
03-15 11:20:40.725 14775 15059 E RootCommands:  at java.io.FileReader.<init>(FileReader.java:58)
03-15 11:20:40.725 14775 15059 E RootCommands:  at org.sufficientlysecure.rootcommands.Remounter.getMounts(Remounter.java:173)
03-15 11:20:40.725 14775 15059 E RootCommands:  at org.sufficientlysecure.rootcommands.Remounter.remount(Remounter.java:66)
03-15 11:20:40.725 14775 15059 E RootCommands:  at org.sufficientlysecure.rootcommands.Toolbox.remount(Toolbox.java:733)
03-15 11:20:40.725 14775 15059 E RootCommands:  at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:164)
03-15 11:20:40.725 14775 15059 E RootCommands:  at org.adaway.service.ApplyService.apply(ApplyService.java:420)
03-15 11:20:40.725 14775 15059 E RootCommands:  at org.adaway.service.ApplyService.doWakefulWork(ApplyService.java:100)
03-15 11:20:40.725 14775 15059 E RootCommands:  at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:100)
03-15 11:20:40.725 14775 15059 E RootCommands:  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
03-15 11:20:40.725 14775 15059 E RootCommands:  at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 11:20:40.725 14775 15059 E RootCommands:  at android.os.Looper.loop(Looper.java:148)
03-15 11:20:40.725 14775 15059 E RootCommands:  at android.os.HandlerThread.run(HandlerThread.java:61)
03-15 11:20:40.726 14775 15059 E AdAway  : Remounting as RW failed! Probably not a problem!
03-15 11:20:40.763 14775 15059 E AdAway  : Exception!
03-15 11:20:40.763 14775 15059 E AdAway  : org.adaway.util.CommandException
03-15 11:20:40.763 14775 15059 E AdAway  :      at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:176)
03-15 11:20:40.763 14775 15059 E AdAway  :      at org.adaway.service.ApplyService.apply(ApplyService.java:420)
03-15 11:20:40.763 14775 15059 E AdAway  :      at org.adaway.service.ApplyService.doWakefulWork(ApplyService.java:100)
03-15 11:20:40.763 14775 15059 E AdAway  :      at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:100)
03-15 11:20:40.763 14775 15059 E AdAway  :      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
03-15 11:20:40.763 14775 15059 E AdAway  :      at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 11:20:40.763 14775 15059 E AdAway  :      at android.os.Looper.loop(Looper.java:148)
03-15 11:20:40.763 14775 15059 E AdAway  :      at android.os.HandlerThread.run(HandlerThread.java:61)
03-15 11:20:40.767 15088 15088 E linker  : normalize_path - invalid input: 'null', the input path should be absolute
03-15 11:20:40.767 15088 15088 W linker  : Warning: unable to normalize "null"
03-15 11:20:40.843 15059 15059 W IntentService[A: type=1400 audit(0.0:836): avc: denied { read } for name="RootToolsMounts" dev="dm-0" ino=752195 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0
03-15 11:20:40.846 14775 15059 E RootCommands: Exception
03-15 11:20:40.846 14775 15059 E RootCommands: java.io.FileNotFoundException: /data/local/RootToolsMounts (Permission denied)
03-15 11:20:40.846 14775 15059 E RootCommands:  at java.io.FileInputStream.open(Native Method)
03-15 11:20:40.846 14775 15059 E RootCommands:  at java.io.FileInputStream.<init>(FileInputStream.java:146)
03-15 11:20:40.846 14775 15059 E RootCommands:  at java.io.FileInputStream.<init>(FileInputStream.java:99)
03-15 11:20:40.846 14775 15059 E RootCommands:  at java.io.FileReader.<init>(FileReader.java:58)
03-15 11:20:40.846 14775 15059 E RootCommands:  at org.sufficientlysecure.rootcommands.Remounter.getMounts(Remounter.java:173)
03-15 11:20:40.846 14775 15059 E RootCommands:  at org.sufficientlysecure.rootcommands.Remounter.remount(Remounter.java:66)
03-15 11:20:40.846 14775 15059 E RootCommands:  at org.sufficientlysecure.rootcommands.Toolbox.remount(Toolbox.java:733)
03-15 11:20:40.846 14775 15059 E RootCommands:  at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:191)
03-15 11:20:40.846 14775 15059 E RootCommands:  at org.adaway.service.ApplyService.apply(ApplyService.java:420)
03-15 11:20:40.846 14775 15059 E RootCommands:  at org.adaway.service.ApplyService.doWakefulWork(ApplyService.java:100)
03-15 11:20:40.846 14775 15059 E RootCommands:  at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:100)
03-15 11:20:40.846 14775 15059 E RootCommands:  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
03-15 11:20:40.846 14775 15059 E RootCommands:  at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 11:20:40.846 14775 15059 E RootCommands:  at android.os.Looper.loop(Looper.java:148)
03-15 11:20:40.846 14775 15059 E RootCommands:  at android.os.HandlerThread.run(HandlerThread.java:61)
03-15 11:20:40.847 14775 15059 E AdAway  : Remounting failed in finally! Probably not a problem!
03-15 11:20:40.847 14775 15059 E AdAway  : Exception:
03-15 11:20:40.847 14775 15059 E AdAway  : org.adaway.util.CommandException
03-15 11:20:40.847 14775 15059 E AdAway  :      at org.adaway.util.ApplyUtils.copyHostsFile(ApplyUtils.java:186)
03-15 11:20:40.847 14775 15059 E AdAway  :      at org.adaway.service.ApplyService.apply(ApplyService.java:420)
03-15 11:20:40.847 14775 15059 E AdAway  :      at org.adaway.service.ApplyService.doWakefulWork(ApplyService.java:100)
03-15 11:20:40.847 14775 15059 E AdAway  :      at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(WakefulIntentService.java:100)
03-15 11:20:40.847 14775 15059 E AdAway  :      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
03-15 11:20:40.847 14775 15059 E AdAway  :      at android.os.Handler.dispatchMessage(Handler.java:102)
03-15 11:20:40.847 14775 15059 E AdAway  :      at android.os.Looper.loop(Looper.java:148)
03-15 11:20:40.847 14775 15059 E AdAway  :      at android.os.HandlerThread.run(HandlerThread.java:61)
03-15 11:20:40.901   937   947 I ActivityManager: START u0 {flg=0x10000004 cmp=org.adaway/.ui.BaseActivity (has extras)} from uid 10197 on display 0
`

**Comment by 0-kaladin** [comment]
you simply need fully working root and/or systemless root with modification.  You can read/post in the xda thread for details: http://forum.xda-developers.com/showthread.php?t=2190753

**Comment by schorsch3000** [comment]
That's a 500+ pages thread, would you mind pointing us to a post or a Page that contains useful information for this exact problem?
