### ISSUE TITLE
unsecure SSL certificate for https://adaway.org

### ISSUE THREAD

**Issue by TraderStf** [Free-Software-for-Android/AdAway#737]
Hello,
If you switch on the filter ~"Consider SHA-1 Certificate as unsecure in Mac Safari", the site is just shown as HTTP.

You can get several 'better' certificates, all details and tools on my ugly page :-)
https://www.moureau.me/best-free-tools/freebies-utilities-software.html

**Comment by 0-kaladin** [comment]
https://adaway.org redirects me to https://free-software-for-android.github.io/AdAway/
which has a sha-2 cert.  Its hosted at github and I didn't even look how that works right now but if I needed a good cert today i'd be using letsencrypt.org where possible.

**Comment by TraderStf** [comment]
That redirection was not existing when I wrote this, good thing now.

**Comment by 0-kaladin** [comment]
good deal then, just wanted to be sure.
