### ISSUE TITLE
Adaway damaged my sd card!

### ISSUE THREAD

**Issue by sporttster** [Free-Software-for-Android/AdAway#740]
So I installed Adaway today hoping to get some relief from all the ads and after a reboot my MXPE says 'SD card is damaged, do you want to reformat?'. W T F!! Is all my stuff on my sd card now fked?? Needless to say I instantly uninstalled adaway and now I've got a sd card issue to deal with. WTH Adaway???? Seriously????

**Comment by dschuermann** [comment]
correlation is not causation

**Comment by sporttster** [comment]
Yeah, it is. My card was fine until this app was installed. How is that not cause???
