### ISSUE TITLE
theChive not working on new phone

### ISSUE THREAD

**Issue by chris5a** [Free-Software-for-Android/AdAway#744]
theChive app not working when AdAway is enabled. I can still get to the website using chrome. 

I tried adding *.thechive.com as well as *chive* to the white list and that did not have any effect. The app opens and the loading page with a picture in the background with the works theChive displays and fails to get past that when AdAway is enabled. If I disable it and reboot then it works. I turned on TCPDUMP logging but don't notice any sites popping up in the log.

It is not working on my new phone SM-G930F Android version 6.0.1 running AdAway 3.1 (55) with latest updates.
It worked on my old phone SM-G900A Android version 5.0 running AdAway 3.1 (55) says update available.

**Comment by 0-kaladin** [comment]
whitelist 'api.branch.io'
Again not an adaway issue, just an exercise in using the TCPdump feature to figure out what to whitelist.

**Comment by chris5a** [comment]
Thank you very much. That fixed the issue.
