### ISSUE TITLE
Before Android 4.1 versions.

### ISSUE THREAD

**Issue by r1c4rd0** [Free-Software-for-Android/AdAway#760]
Hi, I currently have a device that runs android 4.0.3 with no way to update to a newer version.
I'm trying to install adaway but the newest ones don't work on my device due to requiring 4.1 or higher to run. I'm trying to look for previous versions of adaway, mainly the 2.9.2 version, to use instead but every site I visit that supposedly has it has a different filesize for it which leads me to believe they might have been injected with malware or something. I wanted to use fdroid to get it but the last version it has is 3 versions back, 3.0.2, which is still too high.
Would you know what the correct filesize for adaway 2.9.2 would be or its md5?

**Comment by 0-kaladin** [comment]
I keep 2.9.2 on the XDA thread http://forum.xda-developers.com/showthread.php?t=2190753
Please download from there to ensure you don't get one with malware etc.

**Comment by r1c4rd0** [comment]
Thank you.
