### ISSUE TITLE
Use new F-Droid badge

### ISSUE THREAD

**Issue by mvdan** [Free-Software-for-Android/AdAway#765]
See https://f-droid.org/posts/get-it-on-f-droid-badges/.

**Comment by 0-kaladin** [comment]
ok, i edited the readme.

**Comment by mvdan** [comment]
Note that you ignored the HTML/Markdown code, so the badge is huge. You're also using the longer version of the url.

**Comment by 0-kaladin** [comment]
how do i get the short version of the url?

**Comment by mvdan** [comment]
Read the instructions linked above.

**Comment by 0-kaladin** [comment]
of course i read the instructions, just didn't know YOURAPPID = org.adaway.  thought it was maybe some hash and couldn't find.  I guessed.  All set.
