### ISSUE TITLE
AdAway on Nexus 9 disables on reboot

### ISSUE THREAD

**Issue by PieceKeepr** [Free-Software-for-Android/AdAway#767]
I have tried everything I can think of but this problem persists.  On reboot AdAway will always be disabled.

**Comment by 0-kaladin** [comment]
Per the forums, your dirtyUnicorn rom is messing with what adaway is doing.  go to the DU forum thread and ask them how to stop it from overwriting the hosts file on reboot.  Or don't use adaway and leave whatever they are doing intact.
