### ISSUE TITLE
please add this host to disable injected script ISP in my country indonesia, thx a lot

### ISSUE THREAD

**Issue by novincobra** [Free-Software-for-Android/AdAway#772]
127.0.0.1 cfs2.uzone.id
127.0.0.1 stat01.u-ad.info

**Comment by 0-kaladin** [comment]
@dschuermann controls the adaway hosts.
maybe more info is needed however.  @novincobra which ISP is this?

**Comment by dschuermann** [comment]
better ask hosts-file.net for inclusion. adaway.org only contains mobile ad hosts
