### ISSUE TITLE
Are many users missing a hosts source?

### ISSUE THREAD

**Issue by Gitoffthelawn** [Free-Software-for-Android/AdAway#773]
Not long ago, `hosts-file.net` switched from HTTP to HTTPS.  This is correctly reflected in the source:

https://github.com/Free-Software-for-Android/AdAway/blob/1c2e66752e4065d420fa31bf4bb249d36da5ddea/AdAway/src/main/java/org/adaway/provider/AdAwayDatabase.java#L90

During a transitional period, `hosts-file.net` allowed both HTTP and HTTPS connections.  Now it only supports HTTPS for lists.

For new AdAway users, they will be using the correct protocol, but will existing users get updated?  If not, will many of them now be missing an important hosts source?

**Comment by 0-kaladin** [comment]
this is already fixed.  you can download from xda-labs, the xda [thread](http://forum.xda-developers.com/showthread.php?t=2190753), or wait for f-droid build which I'll label once I ensure the other 2 places caused no issues for anyone.

and yes if people don't update they will lose the hosts source but even without the new version they can simply edit it to https

**Comment by Gitoffthelawn** [comment]
@0-kaladin Sounds good... thanks!
